version: '3.8'

services:
    app:
        build: .
        container_name: laravel-app-container
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
        networks:
            - laravel

    webserver:
        image: nginx:latest
        container_name: nginx-container
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
