server {
    listen 80;
    server_name kartastroek.ru www.kartastroek.ru karta-stroek.ru www.karta-stroek.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kartastroek.ru www.kartastroek.ru;
    root /var/www/html/public;

    ssl_certificate /etc/letsencrypt/live/kartastroek.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kartastroek.ru/privkey.pem;

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.ht {
        deny all;
    }
}

server {
    listen 443 ssl;
    server_name karta-stroek.ru www.karta-stroek.ru;
    root /var/www/html/public;

    ssl_certificate /etc/letsencrypt/live/karta-stroek.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/karta-stroek.ru/privkey.pem;

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.ht {
        deny all;
    }
}
